version: '3'

includes:
  api:
    taskfile: ./projects/ecoindex_api/Taskfile.yml
    dir: ./projects/ecoindex_api/

  cli:
    taskfile: ./projects/ecoindex_cli/Taskfile.yml
    dir: ./projects/ecoindex_cli/

  compute:
    taskfile: ./projects/ecoindex_compute/Taskfile.yml
    dir: ./projects/ecoindex_compute/

  scraper:
    taskfile: ./projects/ecoindex_scraper/Taskfile.yml
    dir: ./projects/ecoindex_scraper/

tasks:
  update-all:
    desc: Update all dependencies
    deps: [api:poetry:update, compute:poetry:update]
    cmds:
      - echo "Update all dependencies"
    silent: true

  check-project:
    desc: Check polylith structure project
    cmds:
      - poetry poly check
  
  tests:
    desc: Run tests
    cmds:
      - poetry run pytest

  tests-coverage:
    desc: Run tests with coverage
    cmds:
      - poetry run pytest --cov-report term-missing:skip-covered --cov=. --cov-config=.coveragerc test