version: '3'

tasks:
  build:
    internal: true
    cmds:
      - echo "docker build -t {{.NAME}} {{.VERSION}} {{.OPTIONS}} ."
      - docker build -t vvatelot/ecoindex-{{.NAME}}:{{.VERSION}} -t vvatelot/ecoindex-{{.NAME}}:latest {{.OPTIONS}} .
    silent: true
