version: '3'

tasks:
  up:
    desc: Start the docker-compose project
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f docker-compose.yml  
    cmds:
      - docker-compose up
    silent: true

  login:
    desc: Login to dockerhub
    cmds:
      - echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin
    silent: true

  publish:
    directory: '{{.USER_WORKING_DIR}}'
    desc: Publish the docker image to dockerhub
    cmds:
      - docker push {{.DOCKERHUB_USERNAME}}/{{.DOCKERHUB_IMAGE_NAME}}:{{.DOCKERHUB_IMAGE_TAG}}
    silent: true
