version: '3'

tasks:
  tests:
    desc: Run tests
    cmds:
      - poetry run pytest

  tests-coverage:
    desc: Run tests with coverage
    cmds:
      - poetry run pytest --cov-report "xml:coverage.xml" --cov=. test
    
  tests-coverage-branch:
    desc: Run tests with coverage for current branch
    cmds:
      - poetry run pytest --cov-report "xml:coverage.xml" --cov=. --picked --mode=branch test

  mypy:
    desc: Run mypy
    cmds:
      - poetry run mypy .
  
  ruff:
    desc: Run ruff
    cmds:
      - poetry run ruff .
  
  quality-branch:
    desc: Run quality checks
    deps: [tests-coverage, mypy, ruff]
    cmds:
      - echo "Quality checks passed"

  default:
    desc: Run quality checks
    deps: [tests-coverage, mypy, ruff]
    cmds:
      - echo "Quality checks passed"