version: '3'

tasks:
  tests:
    desc: Run tests
    cmds:
      - poetry run pytest

  tests-coverage:
    desc: Run tests with coverage
    cmds:
      - poetry run pytest --cov-report term-missing:skip-covered --cov=. --cov-config=.coveragerc test

  mypy:
    desc: Run mypy
    cmds:
      - poetry run mypy .
  
  ruff:
    desc: Run ruff
    cmds:
      - poetry run ruff .

  default:
    desc: Run quality checks
    deps: [tests-coverage, mypy, ruff]
    cmds:
      - echo "Quality checks passed"