version: '3'

includes:
  poetry: ../../tasks/PoetryTaskfile.yml
  docker: ../../tasks/DockerTaskfile.yml
  pypi: ../../tasks/PypiTaskFile.yml

tasks:
  bump:
    desc: Bump the project version with rules:major, minor, patch, premajor, preminor, prepatch or prerelease.
    cmds:
      - task: poetry:bump
        vars:
          PROJECT_NAME: compute
          VERSION_FILE_PATH: "../../components/ecoindex/compute/VERSION"
          VERSION_RULE: "{{.CLI_ARGS}}"
    silent: true