
FROM python:3.11-slim

WORKDIR /code
ENV PYTHONPATH "/code"

RUN pip install poetry
COPY ./ ./
RUN poetry install --only scraper 

RUN poetry run playwright install chromium --with-deps

RUN rm -rf /tmp/dist /var/lib/{apt,dpkg,cache,log}/