FROM python:3.12-slim as requirements-stage

WORKDIR /tmp

RUN pip install poetry
COPY pyproject.toml poetry.lock /tmp/
RUN poetry export --output=requirements.txt --without-hashes


FROM python:3.12-slim
    
ARG wheel=ecoindex_cli-2.24.1-py3-none-any.whl
ENV DOCKER_CONTAINER=true

WORKDIR /code

COPY --from=requirements-stage /tmp/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt 

COPY dist/$wheel $wheel
RUN pip install --no-cache-dir $wheel

RUN playwright install chromium --with-deps

RUN rm -rf $wheel requirements.txt /tmp/dist /var/lib/{apt,dpkg,cache,log}/