
FROM python:3.11-slim

WORKDIR /code
ENV PYTHONPATH "/code"

RUN pip install poetry
COPY ./ ./
RUN poetry install --with scraper --with cli

RUN poetry run playwright install chromium --with-deps
RUN ln -s /code/.venv/bin/ecoindex-cli /usr/bin/

RUN rm -rf /tmp/dist /var/lib/{apt,dpkg,cache,log}/