version: '3'

includes:
  poetry: ../../tasks/PoetryTaskfile.yml
  docker: ../../tasks/DockerTaskfile.yml
  pypi: ../../tasks/PypiTaskFile.yml

vars:
  PROJECT_NAME: cli

tasks:
  bump:
    desc: Bump the CLI version with rules:major, minor, patch, premajor, preminor, prepatch or prerelease.
    cmds:
      - task: poetry:bump
        vars:
          VERSION_FILE_PATH: "../../bases/ecoindex/cli/VERSION"
          VERSION_RULE: "{{.CLI_ARGS}}"
    silent: true
  
  docker-build:
    desc: Build the docker image
    deps: [poetry:build]
    vars:
      VERSION:
        sh: poetry version -s
    cmds:
      - task: docker:build
        vars:
          VERSION: "{{.VERSION}}"
          NAME: "{{.PROJECT_NAME}}"
          OPTIONS: --build-arg="wheel=ecoindex_cli-{{.VERSION}}-py3-none-any.whl"
    silent: true