version: '3'

includes:
  poetry: ../../tasks/PoetryTaskfile.yml
  docker: ../../tasks/DockerTaskfile.yml
  pypi: ../../tasks/PypiTaskFile.yml

vars:
  VERSION:
    sh: poetry version -s
  PROJECT_NAME: cli

tasks:
  bump:
    desc: Bump the CLI version with rules:major, minor, patch, premajor, preminor, prepatch or prerelease.
    cmds:
      - task: poetry:bump
        vars:
          VERSION_FILE_PATH: "../../bases/ecoindex/cli/VERSION"
          VERSION_RULE: "{{.CLI_ARGS}}"
    silent: true
  
  docker-build:
    desc: Build the docker image
    cmds:
      - task: docker:build
        vars:
          DOCKER_IMAGE: vvatelot/ecoindex-{{.PROJECT_NAME}}:{{.VERSION}}
          OPTIONS: --build-arg="wheel=ecoindex_cli-{{.VERSION}}-py3-none-any.whl" -f docker/dockerfile .
    silent: true