name: Publish API Docker images

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Bump the version of the API"
        type: choice
        required: true
        default: "patch"
        options:
          - "patch"
          - "minor"
          - "major"
          - "prepatch"
          - "preminor"
          - "premajor"
env:
  DRAFT: ${{ contains(inputs.bump, 'pre') }}

jobs:
  python_project:
    name: Build ecoindex API python project
    runs-on: ubuntu-latest
    outputs:
      wheel: ${{ steps.wheel.outputs.wheel }}
      api_version: ${{ steps.version.outputs.api_version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Install poetry build project
        run: pip install poetry-multiproject-plugin

      - name: Bump version
        run: task api:bump -- ${{ github.event.inputs.bump }}

      - name: Build
        run: task api:poetry:build

      - name: Upload version to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: bases/ecoindex/backend/VERSION

      - name: Upload pyproject.toml to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pyproject
          path: projects/ecoindex_api/pyproject.toml

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: projects/ecoindex_api/dist

      - name: Output version
        id: version
        run: echo "api_version=$(task api:poetry:version-short)" >> $GITHUB_OUTPUT

      - name: Output wheel
        id: wheel
        run: echo "wheel=ecoindex_api-${{ steps.version.outputs.api_version }}-py3-none-any.whl" >> $GITHUB_OUTPUT

      - name: Output summary
        run: |
          echo "API version ${{ steps.version.outputs.api_version }}" >> $GITHUB_STEP_SUMMARY
          echo "Wheel ${{ steps.wheel.outputs.wheel }}" >> $GITHUB_STEP_SUMMARY

  backend_image:
    name: Build and push backend image to docker hub
    runs-on: ubuntu-latest
    needs: python_project
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download dist from artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: projects/ecoindex_api/dist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: vvatelot/ecoindex-api-backend

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: projects/ecoindex_api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }},vvatelot/ecoindex-api-backend:${{ needs.python_project.outputs.api_version }},${{ !env.DRAFT && 'vvatelot/ecoindex-api-backend:latest' || '' }}
          labels: ${{ steps.meta.outputs.labels }}
          file: projects/ecoindex_api/docker/backend/dockerfile
          build-args: wheel=${{ needs.python_project.outputs.wheel }}

  worker_image:
    name: Build and push worker image to docker hub
    runs-on: ubuntu-latest
    needs: python_project
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download dist from artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: projects/ecoindex_api/dist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: vvatelot/ecoindex-api-worker

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: projects/ecoindex_api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }},vvatelot/ecoindex-api-worker:${{ needs.python_project.outputs.api_version }}
          labels: ${{ steps.meta.outputs.labels }}
          file: projects/ecoindex_api/docker/worker/dockerfile
          build-args: wheel=${{ needs.python_project.outputs.wheel }}

  release:
    name: Create a release
    runs-on: ubuntu-latest
    needs: [backend_image, worker_image, python_project]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Commit files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Bump API version to ${{ needs.python_project.outputs.api_version }}"
          tag: v${{ needs.python_project.outputs.api_version }}@api
          tag_push: "--force"
          add: |
            bases/ecoindex/backend/VERSION
            projects/ecoindex_api/pyproject.toml

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.python_project.outputs.api_version }}@api
          release_name: v${{ needs.python_project.outputs.api_version }}@api
          prerelease: ${{ env.DRAFT }}
          body: |
            Changes in this Release
            - Bump version to ${{ needs.python_project.outputs.api_version }}
            - Update backend image to vvatelot/ecoindex-api-backend:${{ needs.python_project.outputs.api_version }}
            - Update worker image to vvatelot/ecoindex-api-worker:${{ needs.python_project.outputs.api_version }}
