name: Validate project quality

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: write

jobs:
  validate-polylith:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install poetry and plugins
        run: |
          curl -sSL https://install.python-poetry.org | python -
          poetry config virtualenvs.create false
          poetry self add poetry-multiproject-plugin
          poetry self add poetry-polylith-plugin
      - name: Install dependencies
        run: |
          poetry install
      - name: Validate polylith project
        run: |
          task project-check
      - name: Validate code quality
        run: |
          task quality
